### ISSUE TITLE
Help with a well composed summary to replace Bolaji's summary

### ISSUE THREAD

**Issue by Oluwasetemi** [Oluwasetemi/oluwasetemi#3]
You can check my [digital cv website](https://cv.oluwasetemi.dev) or [personal website](https://oluwasetemi.dev) to copy a very show summary. I prefer the summary on my CV.

**Comment by Jamesreally** [comment]
Hi setemi, I am one of your student, I'll like to take this if you don't mind give me a detail of what you want.

**Comment by Oluwasetemi** [comment]
@ChijiokeElijah already did this. Thank @Jamesreally check #5 to see how he fixed it.

**Comment by Oluwasetemi** [comment]
I have to close this
